# Travis CI config for EiT front-end

# Required env vars:
# - DOCKER_REPO
# - DOCKER_USER (secure)
# - DOCKER_PASSWORD (secure)
# - SSH_HOST
# - SSH_USER
# - (automatic encryption keys) (secure)

dist: bionic
language: minimal

services:
  - docker

stages:
- name: test
- name: deploy-registry
  if: type = push
- name: deploy-site
  if: type = push

jobs:
  include:
  # Stage: Testing
  - stage: test
    name: Validate Docker image
    install: true # NOP
    script: manage/docker/build.sh

  # Stage: Deploy to registry
  - stage: deploy-registry
    name: Deploy to registry (bleeding)
    if: (branch = master)
    install: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USER" --password-stdin
    script:
    - docker build -t "$DOCKER_REPO:bleeding" .
    - docker push "$DOCKER_REPO:bleeding"

  # Stage: Deploy to site(s)
  - stage: deploy-site
    name: Deploy to site (bleeding)
    if: (branch = master)
    install:
    - openssl aes-256-cbc -K $encrypted_7e234f378aeb_key -iv $encrypted_7e234f378aeb_iv -in keys/ssh_deploy.key.enc -out keys/ssh_deploy.key -d
    - chmod 600 keys/ssh_deploy.key
    script: ssh -oStrictHostKeyChecking=no -i keys/ssh_deploy.key ${SSH_USER}@${SSH_HOST} bleeding
